db/migrate/20160710205341_create_users.rb, db/migrate/20160710210024_create_services.rb, db/migrate/20160710210934_create_bookings.rb, db/migrate/20160710212137_create_reviews.rb, db/migrate/20160711211326_create_requested_services.rb, db/migrate/20160711213405_create_comments.rb, db/schema.rb
This PR allows us to set up the database with all the following tables: 
- Users (covers both cyclists and mechanics)
- Services offered by mechanics
- Bookings for jobs requested of mechanics by cyclists
- Requested Services to connect bookings to the services they are for
- Comments on bookings
=> Migrations

README.md
Add team members' names to the Readme. Add statement that the project is free & open source.
To do in the future: add a summary of who worked on which parts of the app.
=> Basic update to Readme

app/controllers/application_controller.rb, config/routes.rb
Edit to config/routes.rb
Edit to app/controllers/application_controller.rb
=> Ui root index

app/controllers/bookings_controller.rb, config/routes.rb
Adds service list to bookings controller.
Also adds new and create routes to Bookings with respect to Mechanics.
=> Hotfix bookings controller

app/views/services/_form.html.erb, app/views/services/create.html.erb, app/views/services/delete.html.erb, app/views/services/edit.html.erb, app/views/services/index.html.erb, app/views/services/new.html.erb, app/views/services/show.html.erb, app/views/services/update.html.erb
Display service data in views - only New, Edit, Show. 
Remove superfluous view files - Create, Update, Delete, Index.
(fixes issue with PR #22 where the base branch was accidentally set to master)
=> Business logic views services

app/views/review_of_cyclists/_form.html.erb, app/views/review_of_cyclists/create.html.erb, app/views/review_of_cyclists/edit.html.erb, app/views/review_of_cyclists/index.html.erb, app/views/review_of_cyclists/new.html.erb, app/views/review_of_cyclists/show.html.erb, app/views/review_of_cyclists/update.html.erb, app/views/review_of_mechanics/_form.html.erb, app/views/review_of_mechanics/create.html.erb, app/views/review_of_mechanics/edit.html.erb, app/views/review_of_mechanics/index.html.erb, app/views/review_of_mechanics/new.html.erb, app/views/review_of_mechanics/show.html.erb, app/views/review_of_mechanics/update.html.erb
=> Business logic reviews clean

app/views/comments/create.html.erb, app/views/comments/edit.html.erb, app/views/comments/index.html.erb, app/views/comments/new.html.erb, app/views/comments/show.html.erb, app/views/comments/update.html.erb
Adds new view for creating a new comment on a specific booking.
=> Business logic comments

app/views/bookings/index.html.erb, app/views/bookings/new.html.erb, app/views/bookings/show.html.erb
Add index, new and show views to Bookings.
=> Business logic bookings

app/models/review_of_cyclist.rb, app/models/review_of_mechanic.rb, db/seeds.rb
=> Calculate avg rating

app/controllers/mechanics_controller.rb, app/models/mechanic.rb
This PR adds initial search functionality to the Mechanic model and controller. 
The model has been updated with a scoped search function. The controller has been updated to check for acceptable search params and call the search method if any are present. 
Note, no messages are returned if there are no search results -- this is something that should be added soon.
=> Search mechanics

app/controllers/devise/registrations_controller.rb, app/views/devise/registrations/new.html.erb, app/views/users/sessions/new.html.erb
This PR updates the sign up view and adds a custom registration controller that allows for creation of custom cyclist/mechanic user objects.
=> User registration

app/controllers/bookings_controller.rb, app/models/booking.rb, app/views/bookings/index.html.erb, app/views/bookings/new.html.erb
This pull request alters the Booking controller and views to correctly create bookings (and their related service list) and calculate the total cost of service orders.  Some of the user objects are hardcoded to specific values for test purposes.
=> Schedule bookings

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/pages.js, app/assets/stylesheets/application.css.scss, app/assets/stylesheets/index.css, app/controllers/cyclists_controller.rb, app/views/application/index.html.erb, app/views/cyclists/show.html.erb, app/views/devise/registrations/new.html.erb, app/views/mechanics/show.html.erb, app/views/pages/home.html.erb, app/views/users/sessions/new.html.erb
There is conflict in this PR, likely to do with the users/sign_up form.
Edit: Yes! Was correct, simple fix.
Alot of the code taken out below is a) ERB logic b) javascript and jquery that was moved elsewhere
=> Frontend pt2

app/controllers/bookings_controller.rb, app/controllers/cyclists_controller.rb, app/controllers/mechanics_controller.rb, app/controllers/users/sessions_controller.rb, app/views/bookings/index.html.erb, app/views/bookings/show.html.erb, app/views/devise/registrations/new.html.erb
This PR uses session[:id] to render profile view for user objects to prevent users from viewing or modifying each other's pages.  It also changes the style of the radio buttons in the new registration view and implements and overridden create method in the sessions controller to ensure that users are directed to the correct view after login.
=> Session operations

app/assets/javascripts/mechanics.js, app/assets/stylesheets/application.css.scss, app/assets/stylesheets/bookings.css, app/assets/stylesheets/bookings.scss, app/controllers/users/sessions_controller.rb, app/views/bookings/new.html.erb, app/views/mechanics/show.html.erb, config/initializers/assets.rb
New styled form for New booking now available at /cyclists/:id/bookings/new
- class .slider-padding was added to booking.css
- Pre compiler initializer tag was added to the head
- Also fixed the styling on the button
- All the ERB will now submit through to cyclist/:id/bookings! YAY
Session authentication using Warden was added to:
- sessions_controller.rb
- This will make sure that the session can only access its session pages.
ERB and Form_for loop, now filled into the html.
The loop allow any services that are particular to a mechanic to be added to the booking
Initializer for compiled bookings.css and cyclists.css was fixed in assets.rb
Bookings.css was changed name from bookings.scss
=> Created a styled form for Booking.new

app/views/shared/_navbar.html.erb
Basic improvements to navbar functionality. 
- Functional search field
- Link pedalspace logo to pages/home
- Fix 'Edit Profile' button for logged in users
Things not addressed by this PR: 
- The hamburger menu
- Resizing the logo
=> Improved navbar

app/controllers/mechanics_controller.rb, app/controllers/pages_controller.rb, app/models/mechanic.rb, app/views/pages/home.html.erb
This PR contains a WIP -- at one point, the search field on the home page stopped processing location-based requests, so the associated code (1 line) has been commented out.
=> Improved search

app/views/application/index.html.erb
This is the final styling changes for the index page.
=> This is the final styling commit for the index page.

app/views/application/index.html.erb
=> Fixed mobile menu view

app/controllers/bookings_controller.rb, app/views/bookings/new.html.erb
Cyclists can create new service requests.  Fixed issue with new requests not saving to the database.
=> Fix booking creation issue

app/views/review_of_cyclists/_form.html.erb, app/views/review_of_mechanics/_form.html.erb
Cyclists and Mechanics can now make reviews about each other.  There was an issue that prevented submitted reviews from being saved in the database.
=> Fixed issue with review submissions.

app/views/bookings/index.html.erb, app/views/bookings/show.html.erb
Got rid of the placeholder code.
Minimal style for the .erb to render a view for index of bookings.
--- Added label styling for service history
--- Added icon for the container.
=> Styling for the bookings/index
